#!/bin/bash

set -e

LCRS_DATA_DIR=/usr/share/lcrs

echo "Installing LCRS application menu and shortcuts"

xdg-icon-resource install --noupdate --size 16 $LCRS_DATA_DIR/icon/16/lcrs-lcrs.png
xdg-icon-resource install --noupdate --size 22 $LCRS_DATA_DIR/icon/22/lcrs-lcrs.png
xdg-icon-resource install --noupdate --size 32 $LCRS_DATA_DIR/icon/32/lcrs-lcrs.png
xdg-icon-resource install --noupdate --size 48 $LCRS_DATA_DIR/icon/48/lcrs-lcrs.png
xdg-icon-resource install --noupdate --size 64 $LCRS_DATA_DIR/icon/64/lcrs-lcrs.png
xdg-icon-resource install --size 128 $LCRS_DATA_DIR/icon/128/lcrs-lcrs.png

xdg-desktop-menu install /usr/share/applications/lcrs-master.desktop

echo "Stopping and disabling tftpd-hpa..."
set +e
stop tftpd-hpa 2>/dev/null
set -e
if [ -f /etc/init/tftpd-hpa.conf ]
then
	mv /etc/init/tftpd-hpa.conf /etc/init/tftpd-hpa.disabled
fi

# Link lcrs module to dist dir
echo "Linking LCRS to python path"
export PYTHON_DIST_DIR=`python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"`

if [ ! -d $PYTHON_DIST_DIR/lcrs ]
    then
    echo " -> found $PYTHON_DIST_DIR"
    ln -s /usr/share/pyshared/lcrs $PYTHON_DIST_DIR
else
    echo " -> LCRS already in python path"
fi
